### ISSUE TITLE
Add ability to resend Webhooks when not on latest version

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#102]
If I understand the current webhook implementation, once a new version is detected and a webhook is successfully sent, you can not resend it.  Restarting Argus reenables the ability to send it again.  I can resend a webhook on a service whose deployed version matches the current version.  This seems backward to me.  I want to resend a webhook on a service that is still not up to date, not on a service that is already up to date.  Maybe I am thinking about this in the wrong way???

I have services setup to auto approve with a delay of one hour.  This seems to work 90+ percent of the time.  Occasionally even though the webhook is successfully sent and executed, the version is still not updated.  This is happening as the updates have not replicated throughout CDN when the webhook is pulling the latest docker image as an example.  This time will vary obviously so I settled on an hour as it works most of the time.

Ideally I think from a process flow it would look like this when auto approve is enabled:
```
Interval check
New version is detected
Delay times out
Webhook is executed
Interval check
Version is still not up to date
Webhook is executed again
Interval check
Version is still not up to date
Webhook is executed again
Interval check
Version is up to date
```
Would probably want some max retry around the webhook upgrade `executions` different than retrying the webhook because it failed to send the webhook.  After a few failures, human intervention will probably be required.  No point in staying in that hamster wheel forever.  Thoughts?

**Comment by JosephKav** [comment]
I agree that being able to resend webhooks when it's on the latest version doesn't make much sense. I did this before `deployed_version` support to account for webhooks failing and other service-related changes to be made with the webhooks without needing a new version.

I'll look into enabling resend for upgrades to the latest version. I didn't initially allow this to prevent 2+ people triggering the upgrade at the same time. I'm thinking of storing webhook last run times in the code and showing then as a warning in another modal before the approve one. And I'll add a limit to the frequency that the webhooks can be run, something like every 15s max maybe

**Comment by JosephKav** [comment]
Sorry this is taking so long. I will implement your request, I'm just working on getting code coverage up before I do any more code changes. Would have been a lot easier if I did it from the start but better late than never. I've got it up to ~65%, so not much further to go!

**Comment by samcro1967** [comment]
No worries.  Nothing urgent.  Life comes first.  Curious as to your thoughts on how you are planning to handle Docker image updates.  I would think you might need to know what registry the image is hosted on, the tag to monitor, http or https, username and password, etc. in config.yml.  I have a mix of images locally via http with no auth, Docker Hub, and GHCR.  Then regex against something?  Users could script docker inspect to a file for the regex compression, but not sure what would be compared that would be consistent across all containers.  Maybe use created date?  If the container is up to date, its created date should be newer than the registry date.  Docker hub images do not show image creation date though.  It shows created x number of minutes, hours, days, weeks, months ago.  Looking at images in my local Docker registry, there is no date for the creation.  Might be something I need to add to my pipeline, but that column is also called 'ago'.  Hmmm

**Comment by JosephKav** [comment]
I'm thinking of something like
```yaml
service:
  argus:
    latest_version:
      require:
        regex_version: X
        regex_content: X
        docker:
          type: docker/quay/ghcr
          repo: argus-io/argus
          token: TOKEN
          tag: '{{ version }}' - tag style of the docker images
```

Then this'll do
Docker:
`https://index.docker.io/v1/repositories/releaseargus/argus/tags/{{ version }}`
Quay:
`curl --header 'Authorization: Bearer TOKEN' https://quay.io/api/v1/repository/argus-io/argus`
map to json and see if `{{ version }}` is a key
Docker:
`https://api.github.com/repos/release-argus/Argus/tags`

**Comment by samcro1967** [comment]
Yeah, I would agree.  Keep it as simple as possible.  Wondering if you can harvest some of the code from containrrr/watchtower.  I believe it is written in go.  I see no issue either with part of the lift being in the webhook script itself or a script on the system to generate a file to do a comparison against.  I do that for caddy and its module today.  The simplier the code and the config.yml the better.

**Comment by JosephKav** [comment]
Hey @samcro1967, sorry it's taken so long for me to start working on this, but I'd say that this is done in https://github.com/release-argus/Argus/pull/110. Does that look like it implements what you want?

**Comment by samcro1967** [comment]
I think so.  Couple of questions.
1.  How does this interact with auto approve and its delay?  Auto approve tries once and then after 15 seconds you are able to resend if the version is not upgraded?
2. Is the retry delay configurable?  I would probably want it more like 10 or 20 mins.

**Comment by JosephKav** [comment]
1. if the auto-approved hook/command fails, then after 15s you'd be able to retry it. If it passes it'd do the longer 2 * Interval delay
2. It's configurable in that it will change if you change the interval on the service. I've opted for 2*Interval as if it's getting deployed_version from queries of your own service, then 2 * ensures that deployed_version has been rechecked and should have had time for the upgrade to have been done (1 *, it could have queried just before the approve, so the deployed_version wouldn't be checked before the webhooks could be retried)

**Comment by JosephKav** [comment]
I've just added blocking of sends whilst a delay is in progress (will add something like `service.name.options.delay` to be able to delay everything, including commands. Then you'll be able to override that individually for webhooks like you can now).
It should also now block whilst commands are running/webhooks are sending

**Comment by samcro1967** [comment]
Just wanted to confirm that over the past several days docker containers have been updating without issue.  I did not make any changes to my config.  I am not having to retry the webhook either.  Guessing the delay and retries you added are working their magic.
