### ISSUE TITLE
feat: Stateless config.yml for Kubernetes ConfigMap mounts

### ISSUE THREAD

**Issue by ikaruswill** [release-argus/Argus#106]
**Is your feature request related to a problem? Please describe.**
Thanks for this awesome software. I self-host >30 apps on my own Kubernetes and keeping them up-to-date (without automatic image updates breaking services) is quite a big pain point for me.

Running Argus on Kubernetes, I tried mounting `config.yml` in `/etc/argus` but since ConfigMap mounts in Kubernetes are read-only, this automatically fails as Argus tries to write back to `config.yml` for each service, the `status` key. 

As such, I've had to run an `initContainer` using the same argus image, that mounts the `config.yml` in another location first, and copies it to the final location in `/etc/argus/config.yml` before running the 'real' Argus container.

**Describe the solution you'd like**
For `config.yml` to be stateless so that it can be mounted as read-only. State can be stored somewhere else perhaps in a sqlite DB or another plain `state.yml` file. This also has the benefit of keeping responsibilities separate, where only configuration belongs in `config.yml` and state, elsewhere.

**Describe alternatives you've considered**
I'm currently running the initContainer copy method as described above. The current approach is not breaking anything at the moment, but it's probably the first time I've encountered state stored in the same file as the configuration.

**Additional context**
I'm also versed in Golang and would be happy to help with this feature with a PR.

**Comment by JosephKav** [comment]
I did think about doing a DB initially but then didn't as I thought the condig.yml overwriting would work in all cases still. I haven't done much with config maps, so forgot about them being read-only. I will switch to the DB option you suggest and start on it after I get the code-coverage up. If I get stuck on anything I'll be sure to ask you for some help, thanks :)

**Comment by ikaruswill** [comment]
Thanks for giving this consideration. Appreciate it! Ping me here if you do need a hand!

**Comment by JosephKav** [comment]
Thinking about this ticket, a `state.yml` would be quite quick and easy to implement and the only downside I can see would be with the writes incurred on changing a version in a DB vs writing to the file. Though versions don't change that frequently and this `state.yml` will pretty much never be large, so maybe that's not even an issue. Looking into postgres in Go, it seems to have issues that break cross-compilation and may cause a large increase in the binary size.

Do you have any preference on which I go for? The YAML way would be more user friendly in that it'd be very easy to change the versions/dates in a `state.yml`

**Comment by ikaruswill** [comment]
Hmm I was thinking of file based databases like SQLite or BoltDB. These should be very lightweight in terms of the module requirements and shouldn't increase compilation complexity and binary size significantly.

I have no real preference,

**Comment by ikaruswill** [comment]
Hmm. `argus.db` sounds good actually. 

I did some digging in my own self-hosted apps, and found out these: 
* uptime-kuma uses `kuma.db`
* gotify uses `gotify.db`

I share the same thought that `argus.db` naming will future proof this implementation.

A suggestion is that we should put the db file in its own folder. That should allow volume mounts on the entire folder cleanly.
* uptime-kuma does `db/kuma.db`
* gotify does `data/gotify.db`

**Comment by JosephKav** [comment]
Well it all seems to work... apart from cross-compilation being mostly broken because of SQLite's CGO requirement :'(

**Comment by ikaruswill** [comment]
It is kind of surprising that `modernc.org/sqlite` is an exact drop-in replacement. Nice! I just dug around as well, seems like that's really the best one available with no CGO required. Performance wise I share the same thoughts; it's probable perfectly fine, we won't be juggling more than 1k rows anyways.

Well for `windows/arm` it's not like we're going to have people running windows docker containers anytime soon (the images are in gigabytes), and I don't foresee people running windows servers would be keen on application updates 🤣.

**Comment by JosephKav** [comment]
> It is kind of surprising that `modernc.org/sqlite` is an exact drop-in replacement.

Yeah, surprising and very awesome. Not sure on the exact phrasing of this, but I believe it's because they both implement the `database/sql` package which gives the interfaces/functions, so all that changed is how it does those functions behind the scenes

> Performance wise I share the same thoughts; it's probable perfectly fine, we won't be juggling more than 1k rows anyways.

That'd be more than 1k apps being tracked in my current implementation! I've got it clearing unknown rows on startup.


> Well for `windows/arm` it's not like we're going to have people running windows docker containers anytime soon (the images are in gigabytes), and I don't foresee people running windows servers would be keen on application updates 🤣.

😂

**Comment by ikaruswill** [comment]
Hey there @JosephKav I'm back again after nearly 2 years of being a happy user of Argus. 

I noticed that the `0.17.0` upgrade broke my installation during container startup phase due to `config.yml` being read-only. As mentioned prior in the beginning of this earlier issue, I mount the `config.yml` from a ConfigMap, which will show up as read-only files.

I dug further and found that there was a change [in the `entrypoint.sh`](https://github.com/release-argus/Argus/compare/0.16.0...0.17.0#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R30), specifically here https://github.com/release-argus/Argus/blob/5153e1935d2977e93a7a4123998992c5d4187bde/entrypoint.sh#L26-L30 

This attempts to set owner user and group on the `config.yml` file, which fails when the file is not writable. 

Could we change this step to allow failure by using `chown ${ARGUS_UID}:${ARGUS_GID} || true` and log it as a warning?

**Comment by JosephKav** [comment]
Sorry about that change @ikaruswill! Have just pushed a fix that logs a warning if the chown fails like you suggested

https://github.com/release-argus/Argus/blob/80f2e61fa1526943884da76a9d28e742b8a3351e/entrypoint.sh#L26-L31

**Comment by ikaruswill** [comment]
Hey no worries, thanks a lot for the fix @JosephKav, appreciate your work on this. No rush to push a release, whenever is convenient and appropriate for you!

**Comment by JosephKav** [comment]
Have just pushed a release for you 😄

**Comment by ikaruswill** [comment]
It works! 

```
Switching user UID:GID to 911:911
Applying perms to config.yml and argus.db
chown: /app: Read-only file system
chown: /app/config.yml: Read-only file system
WARNING: Changing the ownership of the config/database failed, so some features may not work
Starting...
```
