### ISSUE TITLE
bug: "skip release" seems to do nothing.

### ISSUE THREAD

**Issue by jrhbcn** [release-argus/Argus#126]
**Describe the bug**
Skip release seems to have stop wroking

**To Reproduce**
1. Use a release with deployed version configure but no webhook to update.
2. Wait for a new release to appear.
3. Click on 'skip release'
4. Nothing happens, still the release is there with "Update available"

**Expected behavior**
Release is removed until next one

**Desktop (please complete the following information):**
 - argus running on docker
 - Version 0.8.0

**Comment by JosephKav** [comment]
From my testing, this is fixed in the `0.8.1` release that's building now

**Comment by jrhbcn** [comment]
Confirmed. It is fixed. Many thanks!!
