### ISSUE TITLE
feat: Support for action to check and update a single service

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#131]
Wondering if you could add a second action button beside the webhook action button (or in the upper right hand corner) that would enable the check and update in the UI if applicable of a single service on demand.  Not sure if that is going to complicate some of the logic around auto_approve, interval, retires, etc.  Hoping maybe you could just ignore all of that logic, and if the UI needs updated, update in the db and UI and reset everything.  If not, do nothing and let those parameters do their thing.

**Comment by JosephKav** [comment]
I could do this. I'll leave it until I do UI editable though as I want it to show the version it would grab when adding a new service. That would require me to make each service goroutine restartable. So when someone edits/adds a service, or uses this refresh option, it'd restarts the query cycle. I'd definitely want to rate-limit this option, maybe even user configurable to avoid the demo-site reaching the GH rate-limit
