### ISSUE TITLE
Add link to Current Version

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#148]
Have another suggestion to turn the text of current version into a link of the URL that is defined in config.yml for the current version so you can open it right from the GUI.  I am going to config.yml to copy the link and paste it into a browser when there is an issue.  Might be nice to be able to just click on it right from the web UI.  Thougths?

**Comment by JosephKav** [comment]
You want it to be a link to the GitHub/URL that it's tracking? Why not just have that as `web_url` and reach it by clicking the service name?

**Comment by samcro1967** [comment]
Should have been more explicit and said deployed version.  The link for the service name (upper left hand corner of a service card) currently takes you to the URL defined in config.yml for the `latest_version`.  My suggestion is to give the option change the `current version` text (lower left hand corner of the a service card) into a link that follows the URL defined for `deployed_version` in config.yml via maybe another parameter of `link_enabled` with a value of true or false and defaulted to false.

I can use the `icon_link_to` for a lot of the apps to just get to the app and see the version directly form the app.  That is the same way Argus is getting the deployed version.  Other apps I get the `deployed_version` via the app API or a text file I am creating with a script to grab the deployed version.  So it is a link that is completely different than the app link in `icon_link_to`.  Would be nice to get to the URL link for `deloyed_version` in a browser directly form Argus and not have to go look it up in the config.yml and paste it into the browser.

Hopefully that makes more sense.

**Comment by JosephKav** [comment]
This sounds super niche. Lots of apps are going to have auth required for API links to get the version, so a link to it would be useless in those cases. And if Argus is already getting the `deployed_version` from the app, why would you need a second link to the app (first being the icon), just for a page which should tell you the same as Argus is

**Comment by samcro1967** [comment]
Agreed, it is not the majority of the use cases.  I would say 20% of my links to deployed version are not to the app itself.  They are to a text file or are using the app's API.  For the API use case I am passing an API token in the URL so authentication is all handled within the URL.  That is the only way Argus can access the API URL to grab the deployed version.  Understand if you don't want to implement it as it is not the majority o the use cases.

**Comment by samcro1967** [comment]
Here is an example.

![image](https://user-images.githubusercontent.com/2319445/186530348-28d6bbbb-6fa4-4e29-a176-1436262c5a70.png)

There is no link from within the app to get to the API links.  So you either have to remember it or go look it up.

The `icon_link_to` just get to the app landing page is `http://osu.bazarr:8096/bazarr/`.   I could point the icon_link_to the API version link and then just remove the unneeded parts to get to the app, but that won't work for text files being served up by my web server.  My thought was to just make it optional defaulted to false so it could just be enabled for the ones that need it.

**Comment by JosephKav** [comment]
But I don't get why you need to visit that URL. What does it provide that Argus doesn't give you?

**Comment by samcro1967** [comment]
All I know from Argus is the query failed.  Don't know if it was not accessible or if there is a regex issue or if the app changed they way the data is being displayed or if a script failed.  First thing I do when there is an issue is validate the deployed_version URL is up and accessible.  Second thing I do is compare the text of the link to the regex in confg.yml and the version of the deployed app.  Sometimes the text file I am comparing is not up to date (cron job may have failed if the service was down).  If everything looks OK, then I run a cli test with debug to help further determine what is failing and why.  Having the link would make troubleshooting steps 1 and 2 a little quicker and easier.

**Comment by JosephKav** [comment]
Sorry, but I'm thinking this is too uncommon/niche to implement. The `deployed_version` URL/format will change very rarely in most cases and having this link wouldn't really help in the initial Argus setup

**Comment by samcro1967** [comment]
Fair enough.  Thanks for considering it.
