### ISSUE TITLE
Ability to list service currently being monitored

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#160]
Looking for a way to get a list of the services that are currently being monitored by Argus from the cli.  I know they are printed in the logs when the container starts, but hoping there is another way to grab them without having to parse docker logs.  :-)

I can run `docker exec -it argus bash -c 'argus' > services.txt` and get them that way.  It tries to start a new instance of argus and fails as the port is already in use, but it does print out the services that are active in config.yaml.  Probably not the best way to go about it.  

Would it be possible to add another cli option such as -config.services that simply lists all of the monitored services each on its own line similarly to how it does in the logs?

**Comment by JosephKav** [comment]
You could use a `grep` to get the services in the config?
```bash
❯ docker exec -it argus bash -c 'egrep "^  ([^ ][^:]+)" -o /app/config.yml'
  release-argus/argus
```

**Comment by samcro1967** [comment]
I thought about something like that, but it also picks up items in the settings, defaults, notify, and webhook blocks whose numbers would vary for users depending on their config.  For now I am using `docker exec -t argus bash -c 'argus -test.service aaa' | sed -e '1,3d'`.  Just giving -test.service an invalid service name and removing the first three lines.

**Comment by samcro1967** [comment]
Closing as my workaround to search for a service that does not exist provides the results needed to automate my needs doe another application.
