### ISSUE TITLE
icon_link_to not updating when changed in config.yml

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#161]
Currently running the latest commit.  I updated the icon_link_to for a service, restarted argus, and the link is not updated.  It still points to the previous url configured.  Tried it in a different browser to rule out browser cache, but still seeing the same results.

**Comment by JosephKav** [comment]
So `icon_link_to` was X, you changed it to Y and restarted but it's still taking you to X?
Argus can't know about X if it's not in config, so I think it may have saved between you changing the config (it would save as X as it started with that var). Could you try stopping the service, changing X to Y and restarting pls? (Maybe change the name of the service or something else that will tell you it's using this changed config)

**Comment by samcro1967** [comment]
it was a PEBKAC issue.  Has two versions of config.yml and was editing the wrong one.
