### ISSUE TITLE
bug: api/v1/version not reporting version

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#179]
**Describe the bug**
Updated the argus container to the latest version .  I am not seeing any version being reported at api/v1/version.

Here is what is being reported:
```
{"version":"","buildDate":"","goVersion":"go1.19.3"}
```

**Comment by JosephKav** [comment]
Yeah I noticed this when I did the release last night. Not sure what's caused that to happen but I'll look into it today

**Comment by JosephKav** [comment]
Found the cause. Was related to my renaming of the `utils` package to `util` and missing the change in the Makefile, so it wasn't giving Go the version.
Have re-released `0.11.0`. The binaries give the version again and the Docker images are just building now
