### ISSUE TITLE
feat: Helm chart

### ISSUE THREAD

**Issue by larsl-net** [release-argus/Argus#186]
**Is your feature request related to a problem? Please describe.**
I am planning to build a Helm Chart for the deployment of Argus.

I would make it available, as a subfolder called `chart` or `helm`.

**Comment by JosephKav** [comment]
Cool. I'm leaning towards `chart`. Was unsure about whether it should be a separate repo but am not too fussed if you'd prefer it here. Look forward to seeing it :)

**Comment by larsl-net** [comment]
I am currently still in the process of thinking for a nice scheme for the values because I plan to include quite a few config options.
So that it works also with Openshift.

We can also use a separate repo for this.

**Comment by larsl-net** [comment]
The current version of the chart can be found in this repo and should already work.
[larsl-net/argus-helm](https://github.com/larsl-net/argus-helm)

Tested with a K3s Cluster version v1.24.8+k3s1
Not yet tested with Openshift

**Comment by JosephKav** [comment]
Nice, thanks for this! ⭐ 
I'd prefer the Helm chart as a separate repo, so would you mind making a PR to merge your repo with [release-argus/Helm](https://github.com/release-argus/Helm) please? I'll try and test this out in the next few days

**Comment by larsl-net** [comment]
@JosephKav GitHub won't let me open a PR. Is it possible that Helm Repo needs a branch first?

**Comment by JosephKav** [comment]
Yeah that was probably it, sorry. I've sorted it now by copying your README
