### ISSUE TITLE
bug: UID and GID error on OpenShift

### ISSUE THREAD

**Issue by larsl-net** [release-argus/Argus#211]
**Describe the bug**
When deploying Argus to OpenShift the `entrypoint.sh` tries to set the `UID` and `GID`. In OpenShift no root is available by default, so the `groupmod`, `usermod` and `chown` commands fail and generate errors in the log. The container starts anyway and Argus works as well.

**To Reproduce**
1. Deploy Argus in OpenShift with the default `scc`

**Expected behavior**
The container should start without generating the errors in the log.

**Additional context**
In OpenShift there are security context constraints that restrict functions to increase security. One of the functions is that all containers start with their own project/namespace specific UID. 
https://docs.openshift.com/container-platform/4.12/authentication/managing-security-context-constraints.html

Inside the container
```sh
/app/data$ id
uid=1000940000(1000940000) gid=0(root) groups=0(root),1000940000
/app/data$ ls -Al
total 28
-rw-r--r--. 1 1000940000 1000940000 12288 Feb 14 19:46 argus.db
```
Log:
```sh
Switching user UID:GID to 1000940000:1000940000
groupmod: Permission denied.
groupmod: cannot lock /etc/group; try again later.
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
Applying perms to config.yml and argus.db
chown: changing ownership of '/app/data/argus.db': Operation not permitted
Password: Starting...
su: Authentication failure
INFO: Found 1 services to monitor:
- release-argus/argus
ERROR: release-argus/argus, Get "http://localhost:8080/api/v1/version": dial tcp [::1]:8080: connect: connection refused
INFO: Listening on 0.0.0.0:8080/
```

**Comment by JosephKav** [comment]
Ah, I don't have any experience with OpenShift but thanks for reporting! I think this would be solved by making it only do the user groupmod/usermod/chown/su if it's uid is 0?
Not sure how useful that stuff is, but it does have a usecase I suppose so not really any gain from removing it
I'll work on the PR tomz :)
