### ISSUE TITLE
feat: Support for Environmental variables

### ISSUE THREAD

**Issue by jajaislanina** [release-argus/Argus#216]
**Is your feature request related to a problem? Please describe.**
We have just started using Argus (awesome tool btw) and while setting it up in Kubernetes we encountered an issue that is blocking us from using it for more use cases - secret handling.
We have to keep all the secrets in git at the moment but we would like to use [external secrets operator](https://external-secrets.io/v0.7.2/) to handle secrets in the future.

**Describe the solution you'd like**
Have an option to override config values using Env variables - mainly secrets such as:
GITHUB_ACCESS_TOKEN
DOCKER_USERNAME
DOCKER_PAT_TOKEN
SLACK_TOKEN
etc.

**Describe alternatives you've considered**
As an alternative, having placeholders in the config file (e.g. ${SLACK_TOKEN} ) and then taking the value from env variable would also work, though not ideal in the spirit of the [12 factor app](https://12factor.net/).

**Additional context**

**Comment by jajaislanina** [comment]
Awesome to hear that @JosephKav

**Comment by initharrington** [comment]
Came to this thread as I have a similar use case using [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets).  I think allowing env variable to be set in the config itself is more extensible but starting out with the predefined ones would work too.
