### ISSUE TITLE
bug: semantic_versioning

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#268]
**Describe the bug**
semantic_versioning option for a service being ignored when refreshing deployed version for a service

**To Reproduce**
1. Edit a service
2. Under options set semantic_versioning to no
3. Under deployed version click refresh

**Expected behavior**
semantic_versioning option for a service should be reflected in the deployed version check .

**Screenshots**
![image](https://github.com/release-argus/Argus/assets/2319445/3a22e37d-84de-4b0a-a56b-f38363315ce6)
![image](https://github.com/release-argus/Argus/assets/2319445/814281f7-0a27-4f37-b5e4-c731f2d97efd)
![image](https://github.com/release-argus/Argus/assets/2319445/99602294-7db1-4ebe-9136-a0589f38460e)
JSON
```
{
  ...
  "version": "1.6.2.3573",
  ...
}
```
**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.04
 - Browser:  Chrome
 - Version:  0.12.0

**Comment by JosephKav** [comment]
Ah, seems like it's an issue with me doing `(boolVal || "")`, which if the bool is false would default it to `""`, so semantic_versioning wouldn't be sent in the query. Switching to the null-coalescing operator `??` here is a fix for this.

Thanks for reporting :), commit/release coming very shortly!

**Comment by samcro1967** [comment]
Confirmed works as expected.  Thanks.
