### ISSUE TITLE
feat: Support for XPATH 

### ISSUE THREAD

**Issue by maxlerebourg** [release-argus/Argus#292]
**Is your feature request related to a problem? Please describe it.**
When I retrieve deployed_version which responds:
```json
{ "bar" : [ { "version" : "0.0.1" } ] }
```
with parameter `json = "bar[0].version" || "bar.0.version" || "bar._0.version"`.
This does not work as expected, the array cannot be explored.
The functionality I'm looking for is the implementation of a solution to easily crawl json.

**Describe the solution you want**
I've started trying to rewrite your implementation of json usage, without success.
And as I come from js/ts development, I thought of the xpath equivalent for golang and found [go xpath implementation](https://github.com/antchfx/xpath) that you can use for html, json and/or xml.

**Additional context**
Maybe you'll need a new parameter for `deployed_release: xpath`, so as not to break the old behavior of `deployed_release: json`.

**Comment by JosephKav** [comment]
I have a PR (#294) that will add support for arrays in the JSON, e.g. `bar[0].version`. I don't see a worthwhile benefit to xPath currently, so would rather this than use a package that could drop in support

**Comment by maxlerebourg** [comment]
That's perfect, thanks a lot. I hope it will be released soon.
