### ISSUE TITLE
get latest release from codeberg.org 

### ISSUE THREAD

**Issue by Famku** [release-argus/Argus#344]
Hi,

I wonder if you can help me to get the latest release from https://codeberg.org/readeck/readeck/releases

Can't find the right RegEx command for this.

**Comment by JosephKav** [comment]
https://codeberg.org/api/v1/repos/readeck/readeck/releases - `tag_name":"([^"]+)"`

https://codeberg.org/readeck/readeck/releases - `tag/([^"]+)`

To find this I just did a `curl https://codeberg.org/readeck/readeck/releases > test` and looked through that file for the format and saw all the tags as
`href="/readeck/readeck/src/tag/0.10.6"`
so just did regex to capture the tag
