### ISSUE TITLE
bug: Duplicate notifications sent

### ISSUE THREAD

**Issue by jajaislanina** [release-argus/Argus#349]
**Describe the bug**
Argus keep re-notifying Slack about new releases. Happens multiple time per day without a clear pattern.
Seems to have started when we upgraded from 0.11.1 to 0.15.0.

**To Reproduce**
It seems relevant only when we are 2 releases behind the Github repo.
1. Monitor a Github repository with 2 releases more than what is currently deployed.
2. Observe duplicate notifications sent multiple times per day

**Expected behavior**
Expected behaviour would be to get one notification and only when new release is created on Github.

**Screenshots**
![image](https://github.com/release-argus/Argus/assets/3975615/34aad0f5-ea4d-4666-8973-effdc24b9c35)

**Additional context**
**Relevant logs:**

<img width="1421" alt="Screenshot 2024-01-15 at 13 49 51" src="https://github.com/release-argus/Argus/assets/3975615/f4b08916-8e7a-4dc3-8561-8d07df8310ae">

<img width="1418" alt="Screenshot 2024-01-15 at 13 49 18" src="https://github.com/release-argus/Argus/assets/3975615/09e72518-9ebe-4eb3-97e4-e52aabaaeac9">

**Comment by JosephKav** [comment]
Hmm, I'd guess that this is related to your 10s interval between queries.

I think something like this happened
* Latest release - 1.25.0 (already notified)
* Something changes in the release such that the API returns 1.24.0 as the latest version (maybe it was set to pre release for <20 seconds?), so it notifies as that's a different version
* 1.25.0 set as latest on GitHub, so Argus finds that change and notifies on it

It's probably unlikely that both those repos had the latest version toggled to prerelease for <20 seconds. Could it be a problem with GitHub's API if you are querying the same repos so frequently?

I'll set one of these repos up 2+ versions behind and see if I can reproduce

**Comment by jajaislanina** [comment]
I doubt the pre-release theory as this happens to numerous repos with 2+ releases but increasing the query interval to 1 hour makes much sense to me.
Looking forward to see what you discover @JosephKav

**Comment by jajaislanina** [comment]
Changed the check interval to 1 hour yesterday - so far no more double notifications.
Actually no more notifications at all since there have been no new releases.
Let's keep this one open a bit more - just until we get at least one new release (shouldn't take long) to confirm the issue is solved.

**Comment by JosephKav** [comment]
```
Jan 17 12:59:33 ansible Argus[22091]: VERBOSE: NethermindETH/Nethermind, Potentially found new releases (new ETag "12e9e940718b55548634b62f62c6dc5a3aeb3a3b19ce941f73a2e28b876df018")
^ Query that returns 1.25.1

Jan 17 13:00:05 ansible Argus[22091]: VERBOSE: NethermindETH/Nethermind, Potentially found new releases (new ETag "ce1c299b3d00590474883cfa8e76d94b8f56cc52ec85b1a6af85d17be2a0193e")
^ New ETag
Jan 17 13:00:06 ansible Argus[22091]: VERBOSE: NethermindETH/Nethermind, Possibly found a new version (From "1.25.1" to "1.25.0"). Checking again
^ That ETag had a different version as latest (was missing 1.25.1)

Jan 17 13:00:07 ansible Argus[22091]: VERBOSE: NethermindETH/Nethermind, Potentially found new releases (new ETag "12e9e940718b55548634b62f62c6dc5a3aeb3a3b19ce941f73a2e28b876df018")
^ Recheck gets that original ETag
Jan 17 13:00:07 ansible Argus[22091]: VERBOSE: NethermindETH/Nethermind, Staying on "1.25.1", second check
^ Which has 1.25.1 as latest
```

This looks like an issue with GitHub's API. I'll just PR this double check when it notices a version change to prevent these duplicate notifications
