### ISSUE TITLE
feat: Support for hardcoded current version

### ISSUE THREAD

**Issue by tibouh** [release-argus/Argus#350]
For some of the projects I follow, the release can be a plugin, a binary or something not running on a web server.
There is thus no URL I can use to check the deployed version.

Would it be possible to add the possibility to use a hardcoded version for the deployed version. This hardcoded version would be automatically updated when clicking on the green V when an update is available.

If the idea is bad or if there is already a workaround for this, please tell me.

Thanks.

**Comment by JosephKav** [comment]
If you had a command/webhook to trigger but no deployed version, you would be stuck on whatever version you started on until you did the approve. So you could just add a command that will trigger the update, or just does nothing (e.g. 'ls' or 'echo ""')

**Comment by niklasweimann** [comment]
For anyone stumbling at this issue: I have used an HTTP-Echo service to trick argus into thinking that a given versionn is installed. So when I see a that a new Version is available I trigger the update and change the url to match the new version.

For Example: One service that is running on version 2.1.0 you could use postmans echo service: [https://postman-echo.com/get?version=2.9.9](https://postman-echo.com/get?version=2.1.0)

I am aware that this (kind of) defeats the point of automated updates, but for some services its simply not possible to monitor them.
