### ISSUE TITLE
bug: not rendering URL to the end

### ISSUE THREAD

**Issue by scsargus** [release-argus/Argus#366]
**Describe the bug**
I try to monitor releases from the jFrog Artifactory website. I can find the releases on the page https://jfrog.com/download-legacy/?product=artifactory. I'm using the regex Artifactory\s+([0-9.]+) to find the release number, but the regex can not find a match.

In DEBUG mode, I can see

` DEBUG: Artifactory (url_commands), Looking through:
"\n<!doctype html>\n<html lang=\"en-US\">\n    <head>\n    \n    \n\n<meta name=\"be:sdk\" content=\"php_sdk_1.5.12\" />\n<meta name=\"be:timer\" content=\"28ms\" />\n<meta name=\"be:orig_url\" content=\"https%3A%2F%2Fjfrog.com%2Fdownload-legacy%2F%3Fproduct%3Dartifactory%26installer%3Ddocker-compose\" />\n<meta name=\"be:norm_url\" content=\"https%3A%2F%2Fjfrog.com%2Fdownload-legacy%2F\" />\n<meta name=\"be:capsule_url\" content=\"https%3A%2F%2Fixfd1-api.bc0a.com%2Fapi%2Fixf%2F1.0.0%2Fget_capsule%2Ff00000000300631%2F01327722242\" />\n<meta name=\"be:api_dt\" content=\"py_2023;pm_11;pd_07;ph_12;pmh_56;p_epoch:1699361801986\" />\n<meta name=\"be:mod_dt\" content=\"py_2023;pm_11;pd_07;ph_12;pmh_56;p_epoch:1699361801986\" />\n<meta name=\"be:diag\" content=\"OjzKx7opDifusSb/aaknZnVCz+cOWbAN2cmmQjIVO4le2YwfIS8EgOBSbjwvUdltgWkMyTFmP++Dnf0WhFOQC9pbosvAJYeluxzcKGY9MwCzc0Nw4sAJyzZm7itCqEFRAPEGRtf181kFOwOc...`

**To Reproduce**
1. Configure a new application to monitor
2. Use https://jfrog.com/download-legacy/?product=artifactory as the URL
3. Use Artifactory\s+([0-9.]+) as regex pattern
4. See the problem in DEBUG mode in syslog

**Expected behavior**
Argus should render the URL to the end, so the pattern can be found.

**Additional context**
I tried to wget the URL and I received the full content of the site. Maybe this helps...?
Thanks a lot for looking at this issue.

**Comment by JosephKav** [comment]
curl'ing that url gives 2.5MB of output, so don't really want to output all that, even in debug. I could change it to output everything, but just don't think there's much use in being able to scroll 40,000 lines as opposed to inspecting the url in the browser/curl

After looking at that URL in the browser, I got `one-version "[^0-9]+([0-9.]+)` to pickup the `6.16.0` version. Unless you want `7.77.5` - `one-version.*[^0-9]+([0-9.]+)`

**Comment by scsargus** [comment]
Thanks a lot. Your explanation was very helpful. I wasn't aware that Argus does not see the same as a user.
In the future I will inspect the urls with curl first.
