### ISSUE TITLE
feat: Add a test connection for notifiers

### ISSUE THREAD

**Issue by bloedboemmel** [release-argus/Argus#368]
**Is your feature request related to a problem? Please describe.**
For myself it's quite hard to understand, if my configuration is working right. Especially notifications webhooks can be a real bitch when creating them

**Describe the solution you'd like**
Like many other services I would like to have a simple button which says "Test notification"  when setting up a new service.

**Describe alternatives you've considered**
None

**Comment by JosephKav** [comment]
Alright, makes sense to add this as the UI does let you test latest/deployed versions, so only natural to also let you test notifiers.
I'll start work on this today
fyi, you can currently test them on the cli with `./argus -test.notify NAME`

**Comment by bloedboemmel** [comment]
Nice, thank you and thanks for the trick :)

**Comment by JosephKav** [comment]
Have finally merged a PR that adds a button for testing into the UI. Hope this helps :)
