### ISSUE TITLE
feat: Add link icons in Edit Service UI

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#371]
Would it be possible to add small link icons to both the latest version and deployed version sections in the Edit Service UI to open the Github or URL links in a new tab for users to easily validate the path is valid and get to the data more quickly?

**Comment by JosephKav** [comment]
If you think that'd be helpful I'll work on adding it in

**Comment by samcro1967** [comment]
Thanks.  That would be great if it could be added.

**Comment by JosephKav** [comment]
Sorry it's taken so long, but I've just got round to the PR for this and am merging it now

**Comment by JosephKav** [comment]
Ah yeah, that's my bad. I forgot to add it in there, thought I'd stashed those changes!
Releasing this fix now

**Comment by samcro1967** [comment]
I am seeing it now.  Thanks.
