### ISSUE TITLE
feat: Add curl to container image

### ISSUE THREAD

**Issue by 7ritn** [release-argus/Argus#393]
**Is your feature request related to a problem? Please describe.**
Due to the container image being a Alpine variant, there are not many apps preinstalled, thus the command to execute for update is a bit useless. 

**Describe the solution you'd like**
By adding curl it would be possible to enable API request to for example podman to update an image.

**Describe alternatives you've considered**
I currently build a custom version of Argus by adding curl myself.

**Comment by JosephKav** [comment]
I'll add this for you now. Didn't account for all the apps that commands may want in the switch to Alpine, apologies
