### ISSUE TITLE
feat: Support for deployed version POST requests

### ISSUE THREAD

**Issue by dannytsang** [release-argus/Argus#397]
**Is your feature request related to a problem? Please describe.**
A way to send body data as part of the deployed version check. I have a service that uses graphql and the query resides in the body.

**Describe the solution you'd like**
An extra parameter to handle body data just like headers.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JosephKav** [comment]
Hi Danny,
Could you give me an example of the query please? Are you sure it can't be done with headers/query params, cause having a body in a GET request isn't generally recommended.
Looking [here](https://graphql.org/learn/serving-over-http/#get-request), they put the
```
{
  me {
    name
  }
}
```
query into the url by adding `?query={me{name}}` to it

**Comment by dannytsang** [comment]
Can I change my request to support POST 🙏

**Comment by JosephKav** [comment]
Yeah okay. I'll work on adding a method select to choose between GET and POST, and if POST is selected, give a field to set the Body

**Comment by JosephKav** [comment]
POST's for deployed versions should work in `0.18.0` 😄
