### ISSUE TITLE
feat: Concat multiple JSON values

### ISSUE THREAD

**Issue by alwe2710** [release-argus/Argus#443]
**Is your feature request related to a problem? Please describe.**
When adding my Proxmox Backup Server I discovered the version and patch are stored in separate values:
`{
  "data": {
    "release": "7",
    "repoid": "***",
    "version": "3.2"
  }
}`
In the current setup I do not know of any way to combine those values to get the result of "3.2.7"

**Describe the solution you'd like**
I would wish for a feature to concatenate multiple JSON values

**Comment by JosephKav** [comment]
You could capture this version with the RegEx templating
`"release": ?"(\d+).*"version": ?"([\d.]+)`
with
`$2.$1`

**Comment by alwe2710** [comment]
Works for me, thank you very much.
I honestly didn't think about that
