### ISSUE TITLE
bug: Choosing Notify global dropdown gives blank screen when it does not match Type

### ISSUE THREAD

**Issue by BaccanoMob** [release-argus/Argus#449]
I have a notify config for ntfy in the config.yml file (for example, say `ntfy_global`).

When I use the WebUI to create a service and then add notify, the notify form pops up. When I select `ntfy_global` in the dropdown, the screen goes blank.

Workaround: Choose the type drop down field first to `ntfy` then choose the global.

Solution: Choosing global should first modify the Type drop down field (possibly disable this field while at it) before setting the global settings.

**Comment by JosephKav** [comment]
Thanks for reporting this :).
Took a look and it seemed to be where it checks whether the `.actions` are for a different notify type. But if the currently selected type didn't have a `.actions`, it would try and loop over undefined and get a TypeError. Fixed this by just defaulting that var to an empty list.
