### ISSUE TITLE
bug: Image checking on some ghcr.io repo ends up with "OCI index found, but Accept header does not support OCI indexes" error

### ISSUE THREAD

**Issue by peterbuga** [release-argus/Argus#459]
**Describe the bug**
Trying to monitor some ghcr.io images end up with the message
```
WARNING: immich-app/immich, ghcr.io/immich-app/immich-server:v1.118.1 - {"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI index found, but Accept header does not support OCI indexes"}]}
```

**To Reproduce**
1. Add `ghcr.io/immich-app/immich-server` with tag `{{ version }}` into latest version section

**Expected behavior**
Properly query ghcr.io repository for images like the one in example.

**Additional context**
A quick search yields a possible fix https://serverfault.com/questions/1164750/manifest-unknown-error-oci-index-found-but-accept-header-does-not-support-oci

I did a search on the code but couldn't find these specific headers present.

**Comment by JosephKav** [comment]
Sorry it took a while for me to get round to, but I have just merged the PR that fixes this. Thanks again for reporting 👍

**Comment by peterbuga** [comment]
Thanks for looking into it! Appreciate the work you've done so far! Looking forward to next release 👍

**Comment by JosephKav** [comment]
Sorry it took me a while to do the release, I just kept adding more and more into it, but `0.19.1` is now available with these changes
