### ISSUE TITLE
Add Webhook Support for Gitea/Drone

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#59]
Please consider adding webhook support for Gitea/Drone.

**Comment by jrhbcn** [comment]
Sorry to reply to this thread (I can open another one if you think it is better and remove this comment). Please also consider using local webhooks. I have [webhook](https://github.com/adnanh/webhook) installed, so I want to call it directly from argus. 

For instance, I have a local webhook that responds to `http://192.168.9.9/hooks/update-docker?container=argus` and calls a local script to update a specific container in the name. I am having no luck settings this up.

Regards,

**Comment by JosephKav** [comment]
@jrhbcn yeah, I think another issues would be best please. I'd definitely like to support [adnanh/WebHook](https://github.com/adnanh/webhook) as I do use it myself (just not for receiving from Argus atm)

**Comment by jrhbcn** [comment]
Done. Let's keep this issue for gitea/drone support.

**Comment by JosephKav** [comment]
Is this still wanted, or did you find out how to get them working in [this](https://github.com/release-argus/Argus/issues/61)?

**Comment by samcro1967** [comment]
I am good to close.  I am able to do what I need with webhooks and the Drone CLI.  Longest pole in the tent was creating a docker image for webhook with docker and drone cli in it.  First image I ever created for an app that did not have one.  Was a good learning experience.
