### ISSUE TITLE
feat: Confused about latest / current / approved versions 

### ISSUE THREAD

**Issue by jrhbcn** [release-argus/Argus#60]
I am somehow confused about how Argus reports the current/latest version and the deployed one. If I understand, if you provide a way to get the deployed version, argus shows the deployed version number with an "info" icon (no latest version is shown). If no way to get the deployed version, argus shows no "info" icon and shows the current version. Is this the current behaviour? If so, I think it would be clearer to show both versions (latest and deployed) always, if no deployed then you can show only latest.

In the case of having a way to get the deployed version and a new version is found in github, an "update available" is shown (no webhooks so only the left blue info icon is shown (so the behaviour seems OK). However, what happens if I update externally the deployed version? Shouldn't argus detect it and automatically remove the "update available" panel? This does not seem to work in my installation, updated a service externally but argus keeps the message even though the deployed version should have changed.

Thanks anyway for this tool, I think it has a lot of potential in selfhosted installations!!!

**Comment by JosephKav** [comment]
So I will be renaming `current_version` to `deployed_version` in the config.yml with [#56](https://github.com/release-argus/Argus/issues/56) as current is meant to track what you have deployed. It was just called current originally as it couldn't track what's deployed with API calls

> I am somehow confused about how Argus reports the current/latest version and the deployed one. If I understand, if you provide a way to get the deployed version, argus shows the deployed version number with an "info" icon (no latest version is shown). If no way to get the deployed version, argus shows no "info" icon and shows the current version. Is this the current behaviour? If so, I think it would be clearer to show both versions (latest and deployed) always, if no deployed then you can show only latest.

Argus should display the version that you have deployed in the UI with that info icon to show you which ones it's tracking deployed through an API/equivalent. The UI should always show what it considers to be the latest release, or info about an update being available if they differ.
When Argus finds a new release, it will send messages (if configured) and then there's 3 cases
- if there's a `deployed_version`, it should show that there's an update available in the web UI - from deployed to latest, with an approval/skip for webhooks if they're configured
- If there is no `deployed_version` but there are `webhooks` to be approved, then `current_version` (soon to be `deployed_version`) won't be updated until those webhooks are sent/skipped. (I've done this as some services don't have APIs to get the version they're running, so we take it as only updated when those webhooks are sent). The UI will show an update is available and want the webhooks actioned
- If there is no `deployed_version` and no `webhooks` then it won't be tracking any deployed_version, so it should just send the notifications and update on the UI


> In the case of having a way to get the deployed version and a new version is found in github, an "update available" is shown (no webhooks so only the left blue info icon is shown (so the behaviour seems OK). However, what happens if I update externally the deployed version? Shouldn't argus detect it and automatically remove the "update available" panel? This does not seem to work in my installation, updated a service externally but argus keeps the message even though the deployed version should have changed.

Yee, Argus should query the `deployed_version` at the same interval as it does the service on github/web. Can it definitely query the `deployed_version` correctly? If you set that up after you setup the service in the config, then it may have just got the `current_version` from that original run but keeps failing to get it from the `deployed_version` query.

I'd say to run `./Argus -test.service NAME_OF_THE_SERVICE_IN_CFG` and check that it can resolve the `deployed_version` correctly

**Comment by jrhbcn** [comment]
Thanks @JosephKav, it is much clearer after your explanation. My deployment is working as you explained (it did read the deployed version once, and then it failed as you suggested).

I think the current/deployed renaming is really needed. I'll let you know how that change goes to help my confusion... :)
