### ISSUE TITLE
feat: can skip releases for a `deployed_service` that has no webhooks

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#62]
I noticed that the webhook buttons do not disappear after a webhook is removed from config.xml.  They persist in the UI, but are disabled.

![image](https://user-images.githubusercontent.com/2319445/169695812-948e2b62-e794-4a17-b4b0-67c6012eabcf.png)

**Comment by JosephKav** [comment]
That's just how I designed it. I believe the info button looked too different otherwise and I wanted it to be a consistent layout/design

**Comment by jrhbcn** [comment]
@JosephKav Would it be possible to skip a release even if a webhook is not defined (but a deployment version is)? Sometimes I just want to skip a release without updating (for instance the .0 home assistant releases or the Unifi release candidates).

**Comment by JosephKav** [comment]
Yeah, I can look into adding this. Just not sure on how I'd discretely signify services that have skipped a version. I do this for those with webhooks by changing the resend icon to a tick

**Comment by samcro1967** [comment]
I would suggest adding "(skipped)" in the description after what is currently called To and remove the webhook buttons.  Might also consider renaming "From" and "To" to current and deployed for consistency, although I think it is intuitive enough as is.

**Comment by jrhbcn** [comment]
Yes, something like @samcro1967 is suggesting sounds fine! I was thinking something similar as to keeping the info and removing the current greyed out "OK" and "cancel" buttons for a "skip" one.

**Comment by JosephKav** [comment]
I don't really want to keep those update available options when you skip a realase as I want the skip to make it easily missed that there is a newer version. Currently, when you skip a release with webhooks, those buttons disappear and the only indicator of the skip is the icon on the resend button becoming a tick. We can't do that as there's nothing to resend in these cases.

I've managed to get it to hide the 'Send' button, but still take up the same space. So here's the options you'll get if there's a deployed_version checker, but no webhooks:
![image](https://user-images.githubusercontent.com/4267227/170490503-5eea70c8-0f57-4e51-b937-0d052d5dfd3c.png)

I'm proposing we add another info icon to display that it's skipped, but just right-align it
![image](https://user-images.githubusercontent.com/4267227/170491053-d83d2249-509c-4314-831b-d06d4ea2aa51.png)

Not sure whether to display that icon if there are webhooks
![image](https://user-images.githubusercontent.com/4267227/170491201-1f4fb80c-86b5-4d89-ab86-82294d05d130.png)
as the resend icon has changed, and the modal that pops up tells you which version it's on and would go to (so what version has been skipped)
![image](https://user-images.githubusercontent.com/4267227/170491299-f2be5b16-ef6c-428c-98b5-bbe20bbe35e9.png)
I'm leaning towards only displaying this 'Skipped VERSION' icon when there are no webhooks

**Comment by JosephKav** [comment]
> So you would click on the info button and get the ability to deploy if a webhook is present?

nothing's changed if you have webhook.s You'll get the options to view info on it, approve it, and skip it

> And you can also skip a version if a webhook is not even present and get the info button?

If you don't have any webhooks (but do have a deployed version it's checking as otherwise the version would update straight away), it'll give you my first picture with the info and skip buttons

**Comment by samcro1967** [comment]
Ah, now I understand.  With no webhook defined, you go straight to skipped.  So the only indication that you are a version behind at that point is the skipped button.  I think that makes sense.  Maybe make the button red so it jumps out.

**Comment by jrhbcn** [comment]
@JosephKav your proposal looks perfect! I would prefer having the skipped icon (maybe with an "s" instead of "i") always (even with webhooks defined) but it is just a small thing. 

Thank you for considering this.

**Comment by JosephKav** [comment]
I do like the look of the S as two of the same icon looks a bit random. Coloured it yellow as a warning that an update's been skipped
![image](https://user-images.githubusercontent.com/4267227/170513647-5539ef8e-a4ad-4893-aaa6-f4ba45402a0a.png)
![image](https://user-images.githubusercontent.com/4267227/170513710-56fe93ff-f6ef-45d6-bd56-69b91f670823.png)

Now I'm not too sure about how to handle the update being skipped and webhooks being available

- no change (tick icon when it's been skipped)
![image](https://user-images.githubusercontent.com/4267227/170514668-350457d8-e9b6-458f-bee5-78d09de86641.png)
- yellow the tick icon
![image](https://user-images.githubusercontent.com/4267227/170515384-8990245d-68c4-4ba8-ac53-200d0b3ba795.png)
- show the S next to the webhook resend
![image](https://user-images.githubusercontent.com/4267227/170516378-cd18ca69-e933-4de2-8b77-1c7f8ab75ca5.png)
I'm slowly coming prefering this this over the yellow tick. What are your thoughts?
![image](https://user-images.githubusercontent.com/4267227/170516480-67db9707-62df-403a-853e-6457f5b88a2d.png)

**Comment by jrhbcn** [comment]
I buy the "S" icon myself :)

**Comment by JosephKav** [comment]
I've merged this feature to `master` now. Will do a release after adding send/resend for [commands](https://github.com/release-argus/Argus/pull/70) to the UI

**Comment by jrhbcn** [comment]
Thanks yet again, working perfect now!
