### ISSUE TITLE
Versioning Determination Question around Beta's and pre-releases

### ISSUE THREAD

**Issue by samcro1967** [release-argus/Argus#78]
Some apps I am monitoring have beta's and release candidates available.  Grafana is an example where I am running 9.0.0-beta2 and the most recent version is 8.5.4.  The first version listed on their Github release page is 8.5.4.  I could add an index, but the position of the version I am running may not always be at the same index.  Syncthing is another example.  I am running 1.20.1, but the first version listed on their Github release page is 1.20.2-rc.3.  It has additional complexity as I run the LSIO image which has its own versions and tags on Github and Docker Hub that differ slightly.

They are marked (didn't want to use the word tag) on their release page as latest, beta, and pre release, but they are a few hundred lines apart in the html code.  Not sure regex is going to solve that problem.  Not quite sure what to try or suggest to tackle the problem.

Here is how Syncthing looks.  Not suite sure what the pre-release bubble is really called and if that is common on most repos.
![Untitled](https://user-images.githubusercontent.com/2319445/171290788-1ab2bb49-04e9-4159-8512-a0add992788f.jpg)

Wondering if you have any thoughts on the best way to approach it.  It would be good to know what the "latest" version is as well if there are beta's or pre releases also available, maybe in the current version bubble in Argus or somethign.  Thinking somehow one could define in config.xml what release cannel you wanted to be on (latest, beta, prerelease, nightly, dev, etc.).  Not sure that will be easy to do with code and would be consistent enough across repos.

I have this on 3 out of 40 services in this state now, so it is a small percentage.  And, in theory, those services would only be in that state for a few weeks or months until the upgrades are complete.  Thought I would at least log an issue to get a few ideas.

**Comment by JosephKav** [comment]
You can track GitHub pre-releases if you `use_prerelease: true`
I don't think I want to add tracking of latest/beta/dev/other all under 1 service in Argus as the way these are named/done can vary massively between developers. If you wanted to know the latest release candidate of Syncthing for example, you'd need to add that `use_prerelease` and then just make the `url_command` regex something like `v([0-9.]+-rc\.[0-9])`.
You could track the latest Syncthing release number (whether it be a stable release, or rc) with `use_prerelease` and `v(.*)` as Argus sorts the versions it gets if `semantic_versioning` is true (default). '1.20.2-rc.2' follows semantic versioning so 
```yaml
  syncthing/syncthing:
    type: github
    url: syncthing/syncthing
    url_commands:
      - type: regex
        regex: v(.*)
    use_prerelease: true
```
gets that:
```bash
❯ ./argus -test.service syncthing/syncthing
INFO: Testing (syncthing/syncthing),
INFO: syncthing/syncthing, Latest Release - "1.20.2-rc.2"
```

**Comment by samcro1967** [comment]
Ok.  Got some time to test this and using `use_prerelease` I was able to adjust the three in question and get their status to what I wanted.  Did not remember that was an option.  Thanks!
